"""
PPTX 转图片工具函数。

优先支持 Windows 流程：
1) pptxtopdf.convert: PPTX -> PDF
2) pdf2image.convert_from_path: PDF -> PIL Image

Linux/WSL 下回退：
1) soffice --headless: PPTX -> PDF
2) pdftoppm: PDF -> PNG
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path


def require_binary(name: str) -> None:
    if shutil.which(name) is None:
        raise RuntimeError(
            f"Missing dependency: '{name}'. "
            "Install it first (e.g. apt-get install libreoffice-impress poppler-utils)."
        )


def run_cmd(command: list[str]) -> None:
    subprocess.run(command, check=True)  # noqa: S603


def _convert_pdf_to_png_windows(
    pdf_path: Path,
    output_png: Path,
    dpi: int,
    poppler_path: str | None,
) -> None:
    try:
        from pdf2image import convert_from_path
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(
            "Missing dependency 'pdf2image'. Install with: pip install pdf2image"
        ) from exc

    kwargs = {"dpi": dpi, "first_page": 1, "last_page": 1}
    if poppler_path:
        kwargs["poppler_path"] = poppler_path
    images = convert_from_path(str(pdf_path), **kwargs)
    if not images:
        raise RuntimeError(f"No image rendered from PDF: {pdf_path}")
    output_png.parent.mkdir(parents=True, exist_ok=True)
    images[0].save(output_png, format="PNG")


def _convert_pptx_to_pdf_windows(pptx_path: Path, out_dir: Path) -> Path:
    try:
        from pptxtopdf import convert
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(
            "Missing dependency 'pptxtopdf'. Install with: pip install pptxtopdf"
        ) from exc

    out_dir.mkdir(parents=True, exist_ok=True)
    convert(input_path=str(pptx_path), output_folder_path=str(out_dir))
    pdf_path = out_dir / f"{pptx_path.stem}.pdf"
    if not pdf_path.exists():
        raise RuntimeError(f"PDF not generated by pptxtopdf: {pdf_path}")
    return pdf_path


def _convert_pptx_to_pdf_libreoffice(pptx_path: Path, out_dir: Path) -> Path:
    require_binary("soffice")
    run_cmd(
        [
            "soffice",
            "--headless",
            "--nologo",
            "--nodefault",
            "--nolockcheck",
            "--convert-to",
            "pdf",
            "--outdir",
            str(out_dir),
            str(pptx_path),
        ]
    )
    pdf_path = out_dir / f"{pptx_path.stem}.pdf"
    if not pdf_path.exists():
        raise RuntimeError(f"PDF not generated by soffice: {pdf_path}")
    return pdf_path


def _convert_pdf_to_png_libreoffice(pdf_path: Path, output_png: Path, dpi: int) -> None:
    require_binary("pdftoppm")
    output_png.parent.mkdir(parents=True, exist_ok=True)
    output_prefix = output_png.with_suffix("")
    run_cmd(
        [
            "pdftoppm",
            "-png",
            "-f",
            "1",
            "-l",
            "1",
            "-singlefile",
            "-rx",
            str(dpi),
            "-ry",
            str(dpi),
            str(pdf_path),
            str(output_prefix),
        ]
    )


def convert_pptx_first_page_to_png(
    pptx_path: Path,
    output_png: Path,
    dpi: int = 200,
    backend: str = "auto",
    poppler_path: str | None = None,
) -> Path:
    """
    将 PPTX 首页转换为 PNG。

    Args:
        pptx_path: 源 PPTX 路径
        output_png: 输出 PNG 路径
        dpi: 渲染 DPI
        backend: auto | windows | libreoffice
        poppler_path: Windows 下可选 poppler bin 路径
    """
    pptx_path = Path(pptx_path)
    output_png = Path(output_png)

    if not pptx_path.exists():
        raise FileNotFoundError(f"PPTX not found: {pptx_path}")

    with tempfile.TemporaryDirectory(prefix="pptx2png_") as tmp_dir:
        tmp_dir_path = Path(tmp_dir)
        backend_used = backend.lower()
        if backend_used == "auto":
            backend_used = "windows" if os.name == "nt" else "libreoffice"

        if backend_used == "windows":
            pdf_path = _convert_pptx_to_pdf_windows(pptx_path, tmp_dir_path)
            _convert_pdf_to_png_windows(pdf_path, output_png, dpi=dpi, poppler_path=poppler_path)
        elif backend_used == "libreoffice":
            pdf_path = _convert_pptx_to_pdf_libreoffice(pptx_path, tmp_dir_path)
            _convert_pdf_to_png_libreoffice(pdf_path, output_png, dpi=dpi)
        else:
            raise ValueError(f"Unsupported backend: {backend}")

    if not output_png.exists():
        raise RuntimeError(f"PNG not generated for: {pptx_path}")
    return output_png
